version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres-docker-container
    restart: always
    ports:
      - "5436:5432"
    network_mode: host
    # volumes:
    #   - .:/docker-entrypoint-initdb.d/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres", "--dbname", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  goapp:
    image: golang-docker-container
    build:
      context: .
      dockerfile: Dockerfile.golang
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    ports:
      - "5432:5432"